export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILURE = 'SEARCH_USER_FAILURE';

export const GET_USER_REPOSITORIES_REQUEST = 'GET_USER_REPOSITORIES_REQUEST';
export const GET_USER_REPOSITORIES_SUCCESS = 'GET_USER_REPOSITORIES_SUCCESS';
export const GET_USER_REPOSITORIES_FAILURE = 'GET_USER_REPOSITORIES_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_REPOSITORY_COMMITS_REQUEST = 'GET_REPOSITORY_COMMITS_REQUEST';
export const GET_REPOSITORY_COMMITS_SUCCESS = 'GET_REPOSITORY_COMMITS_SUCCESS';
export const GET_REPOSITORY_COMMITS_FAILURE = 'GET_REPOSITORY_COMMITS_FAILURE';

export const CLEAR_REPOSITORY = 'CLEAR_REPOSITORY';

export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
