export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILURE = 'SEARCH_USER_FAILURE';

export const USER_REPOSITORIES_REQUEST = 'USER_REPOSITORIES_REQUEST';
export const USER_REPOSITORIES_SUCCESS = 'USER_REPOSITORIES_SUCCESS';
export const USER_REPOSITORIES_FAILURE = 'USER_REPOSITORIES_FAILURE';